-- DV-052 -- the Target model brought onto the contract, and the position question settled.
--
-- Five of the twelve Build Plan section 01 targets are solar-system bodies. A stored
-- J2000 coordinate for Jupiter is false the day after it is written, so coordinates are
-- now nullable and positionSource says which kind of target this is. The CHECK at the
-- bottom makes the invariant the database's business rather than the application's.
--
-- DESTRUCTIVE: currentVisibility, currentAltitude and qualityScore are dropped, and the
-- VisibilityRating enum with them. They cached observability, which both the contract
-- ("computed at request time from live ephemeris, never cached as a static list") and
-- Build Plan section 01 ("the scheduler computes these at request time -- never from a
-- static list") forbid. imagePreset, bestMonths and the old angularSize string go too:
-- the contract models size as a number in arcminutes.
--
-- Safe because no database holding real rows has been deployed. Target rows are seeded
-- catalogue data, regenerated by the seed.

-- ---------------------------------------------------------------------------
-- CATALOGUE PURGE -- READ BEFORE APPLYING TO ANY DATABASE YOU CARE ABOUT.
--
-- The new columns have no derivable value for an existing row. angularSizeArcmin
-- cannot be recovered from the old free-text angularSize ("190 x 60 arcmin"), and
-- opticalConfig and imagingProfile never existed. A backfill would mean inventing
-- the optical configuration for each target, which is a physical fact about the
-- instrument and not something a migration may guess.
--
-- So the catalogue is emptied and re-seeded from Build Plan section 01. Because
-- missions, bookings and captures reference targets with ON DELETE RESTRICT, they
-- are removed first. In this repository every such row is seeded demo data.
--
-- This is safe now, before launch, and never again. Once a real customer has an
-- observation, this migration would destroy it. It must not be re-run against a
-- populated database.
-- ---------------------------------------------------------------------------
DELETE FROM "CaptureAsset";
DELETE FROM "CaptureAccess";
DELETE FROM "CollectionCapture";
DELETE FROM "Capture";
DELETE FROM "MissionEvent";
DELETE FROM "MissionParticipant";
DELETE FROM "MissionPresence";
DELETE FROM "PrivateSession";
DELETE FROM "Booking";
DELETE FROM "Mission";
DELETE FROM "TargetObservatory";
DELETE FROM "Target";

-- CreateEnum
CREATE TYPE "TargetPositionSource" AS ENUM ('FIXED', 'EPHEMERIS');

-- CreateEnum
CREATE TYPE "SolarSystemBody" AS ENUM ('MOON', 'MERCURY', 'VENUS', 'MARS', 'JUPITER', 'SATURN', 'URANUS', 'NEPTUNE');

-- DropIndex
DROP INDEX "Target_type_currentVisibility_qualityScore_idx";

-- AlterTable
ALTER TABLE "Target" DROP COLUMN "angularSize",
DROP COLUMN "bestMonths",
DROP COLUMN "commonName",
DROP COLUMN "currentAltitude",
DROP COLUMN "currentVisibility",
DROP COLUMN "georgianName",
DROP COLUMN "imagePreset",
DROP COLUMN "minimumAltitude",
DROP COLUMN "preferredObservationDurationMinutes",
DROP COLUMN "qualityScore",
ADD COLUMN     "angularSizeArcmin" DOUBLE PRECISION NOT NULL,
ADD COLUMN     "enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "expectedMissionMinutes" INTEGER NOT NULL,
ADD COLUMN     "imagingProfile" "ImagingProfile" NOT NULL,
ADD COLUMN     "minAltitudeDegrees" DOUBLE PRECISION NOT NULL,
ADD COLUMN     "nameEn" TEXT NOT NULL,
ADD COLUMN     "nameKa" TEXT NOT NULL,
ADD COLUMN     "opticalConfig" "OpticalConfig" NOT NULL,
ADD COLUMN     "positionSource" "TargetPositionSource" NOT NULL,
ADD COLUMN     "previewImageUrl" TEXT,
ADD COLUMN     "solarSystemBody" "SolarSystemBody",
ALTER COLUMN "catalogId" DROP NOT NULL,
ALTER COLUMN "rightAscensionHours" DROP NOT NULL,
ALTER COLUMN "declinationDegrees" DROP NOT NULL,
ALTER COLUMN "descriptionEn" DROP NOT NULL,
ALTER COLUMN "descriptionKa" DROP NOT NULL;

-- DropEnum
DROP TYPE "VisibilityRating";

-- CreateIndex
CREATE INDEX "Target_type_enabled_idx" ON "Target"("type", "enabled");


-- AddConstraint
-- Exactly one position source, enforced where it cannot be bypassed. Prisma cannot
-- express a CHECK constraint, so it is written by hand.
ALTER TABLE "Target" ADD CONSTRAINT "target_position_source_consistent" CHECK (
  ("positionSource" = 'FIXED'
     AND "rightAscensionHours" IS NOT NULL
     AND "declinationDegrees"  IS NOT NULL
     AND "solarSystemBody"     IS NULL)
  OR
  ("positionSource" = 'EPHEMERIS'
     AND "solarSystemBody"     IS NOT NULL
     AND "rightAscensionHours" IS NULL
     AND "declinationDegrees"  IS NULL)
);
