# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import (AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr,
                      Field, RootModel)


class Locale(StrEnum):
    """
    Darkview ships Georgian and English from the first commit.
    """
    en = 'en'
    ka = 'ka'


class Currency(RootModel[Literal['GEL']]):
    root: Literal['GEL']


class UserRole(StrEnum):
    user = 'USER'
    operator = 'OPERATOR'


class ErrorCode(StrEnum):
    bad_request = 'BAD_REQUEST'
    unauthenticated = 'UNAUTHENTICATED'
    forbidden = 'FORBIDDEN'
    not_found = 'NOT_FOUND'
    conflict = 'CONFLICT'
    validation_failed = 'VALIDATION_FAILED'
    slot_unavailable = 'SLOT_UNAVAILABLE'
    payment_required = 'PAYMENT_REQUIRED'
    payment_failed = 'PAYMENT_FAILED'
    session_not_owner = 'SESSION_NOT_OWNER'
    mission_not_active = 'MISSION_NOT_ACTIVE'
    mission_not_observable = 'MISSION_NOT_OBSERVABLE'
    observer_capacity_reached = 'OBSERVER_CAPACITY_REACHED'
    observer_cannot_command = 'OBSERVER_CANNOT_COMMAND'
    observatory_offline = 'OBSERVATORY_OFFLINE'
    weather_hold = 'WEATHER_HOLD'
    safety_refused = 'SAFETY_REFUSED'
    safety_not_configured = 'SAFETY_NOT_CONFIGURED'
    rate_limited = 'RATE_LIMITED'
    internal = 'INTERNAL'


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: ErrorCode
    message: str = Field(..., description='Human-readable, English. Client-facing copy is localised client-side from `code`.')
    details: dict[str, Any] | None = Field(None, description='Optional structured detail. Never contains a secret, device address or credential.')


class PageMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    has_more: bool = Field(..., alias='hasMore')
    next_cursor: str | None = Field(None, alias='nextCursor')


class EquatorialCoordinates(BaseModel):
    """
    J2000 equatorial coordinates. Conversion to apparent coordinates happens at the device boundary inside the agent, never in a client.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    ra_hours: float = Field(..., alias='raHours', ge=0.0, lt=24.0)
    dec_degrees: float = Field(..., alias='decDegrees', ge=-90.0, le=90.0)
    epoch: Literal['J2000']


class HorizontalCoordinates(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    altitude_degrees: float = Field(..., alias='altitudeDegrees', ge=-90.0, le=90.0)
    azimuth_degrees: float = Field(..., alias='azimuthDegrees', ge=0.0, lt=360.0)


class User(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    email: EmailStr
    display_name: str | None = Field(None, alias='displayName')
    role: UserRole
    locale: Locale
    created_at: AwareDatetime = Field(..., alias='createdAt')


class TargetType(StrEnum):
    """
    Phase 1 catalogue classes only. Every class in this enum is one the
    NexStar 6SE + ASI585MC combination can present convincingly from a Bortle 8-9
    sky. Wide targets that do not fit any available field of view are excluded from
    the catalogue and therefore from this enum.

    """
    moon = 'MOON'
    planet = 'PLANET'
    double_star = 'DOUBLE_STAR'
    globular_cluster = 'GLOBULAR_CLUSTER'
    planetary_nebula = 'PLANETARY_NEBULA'
    bright_nebula = 'BRIGHT_NEBULA'


class SolarSystemBody(StrEnum):
    """
    A body whose position is computed from ephemeris at request time. Phase 1
    offers the Moon and the four planets the Build Plan lists; the rest are
    named so the enum does not need a breaking change to add one.

    """
    moon = 'MOON'
    mercury = 'MERCURY'
    venus = 'VENUS'
    mars = 'MARS'
    jupiter = 'JUPITER'
    saturn = 'SATURN'
    uranus = 'URANUS'
    neptune = 'NEPTUNE'


class TargetPositionSource(StrEnum):
    """
    Where a target's position comes from. FIXED targets carry J2000
    coordinates. EPHEMERIS targets do not have any: the Moon and the planets
    move, and a stored coordinate for one is a statement that is false the day
    after it is written. Their position is computed at request time from
    solarSystemBody.

    """
    fixed = 'FIXED'
    ephemeris = 'EPHEMERIS'


class OpticalConfig(StrEnum):
    """
    The three optical configurations of the C6. Focal length and image scale follow
    from the choice. F20_BARLOW = 3000 mm, F10_NATIVE = 1500 mm,
    F6_3_REDUCER = 945 mm with the #94175 reducer.

    """
    f20_barlow = 'F20_BARLOW'
    f10_native = 'F10_NATIVE'
    f6_3_reducer = 'F6_3_REDUCER'


class ImagingProfile(StrEnum):
    """
    Short-exposure / live-stacking profiles only. Phase 1 is a live-view (EAA)
    experience. There is no long-exposure profile and none may be added without an
    approved decision record.

    """
    lunar = 'LUNAR'
    planetary = 'PLANETARY'
    double_star = 'DOUBLE_STAR'
    globular_cluster = 'GLOBULAR_CLUSTER'
    planetary_nebula = 'PLANETARY_NEBULA'
    bright_nebula = 'BRIGHT_NEBULA'


class Target(BaseModel):
    """
    A catalogue object. Exactly one of `coordinates` or `solarSystemBody` is
    present, decided by `positionSource`: a FIXED target has coordinates and no
    body, an EPHEMERIS target has a body and no coordinates.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    slug: str = Field(..., pattern='^[a-z0-9-]+$')
    catalog_id: str | None = Field(None, alias='catalogId', description='Catalogue designation, for example "M13" or "NGC 6205".')
    type: TargetType
    name_en: str = Field(..., alias='nameEn')
    name_ka: str = Field(..., alias='nameKa')
    description_en: str | None = Field(None, alias='descriptionEn')
    description_ka: str | None = Field(None, alias='descriptionKa')
    position_source: TargetPositionSource = Field(..., alias='positionSource')
    coordinates: EquatorialCoordinates | None = Field(None, description='J2000 coordinates. Present only when positionSource is FIXED.')
    solar_system_body: SolarSystemBody | None = Field(None, alias='solarSystemBody', description='Present only when positionSource is EPHEMERIS.')
    angular_size_arcmin: float = Field(..., alias='angularSizeArcmin', gt=0.0)
    magnitude: float
    optical_config: OpticalConfig = Field(..., alias='opticalConfig')
    imaging_profile: ImagingProfile = Field(..., alias='imagingProfile')
    min_altitude_degrees: float = Field(..., alias='minAltitudeDegrees', ge=0.0, le=90.0)
    expected_mission_minutes: int = Field(..., alias='expectedMissionMinutes', gt=0)
    preview_image_url: AnyUrl | None = Field(None, alias='previewImageUrl', description='Must be an image this telescope actually produced. Never a stock image and\nnever output from a professional instrument presented as Darkview output.\n')
    enabled: bool


class TargetPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Target]
    page: PageMeta


class VisibilityBlockReason(StrEnum):
    below_min_altitude = 'BELOW_MIN_ALTITUDE'
    above_max_altitude = 'ABOVE_MAX_ALTITUDE'
    behind_horizon_mask = 'BEHIND_HORIZON_MASK'
    in_forbidden_azimuth = 'IN_FORBIDDEN_AZIMUTH'
    sun_too_high = 'SUN_TOO_HIGH'
    too_close_to_sun = 'TOO_CLOSE_TO_SUN'
    too_close_to_moon = 'TOO_CLOSE_TO_MOON'
    does_not_fit_field = 'DOES_NOT_FIT_FIELD'
    below_horizon = 'BELOW_HORIZON'
    target_disabled = 'TARGET_DISABLED'
    weather_hold = 'WEATHER_HOLD'
    observatory_offline = 'OBSERVATORY_OFFLINE'
    safety_envelope_unmeasured = 'SAFETY_ENVELOPE_UNMEASURED'


class TargetVisibility(BaseModel):
    """
    Computed at request time from live ephemeris. Never cached as a static list.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    observable: bool
    evaluated_at: AwareDatetime = Field(..., alias='evaluatedAt')
    horizontal: HorizontalCoordinates
    sun_altitude_degrees: float = Field(..., alias='sunAltitudeDegrees')
    moon_separation_degrees: float = Field(..., alias='moonSeparationDegrees')
    rises_at: AwareDatetime | None = Field(None, alias='risesAt')
    sets_at: AwareDatetime | None = Field(None, alias='setsAt')
    block_reasons: list[VisibilityBlockReason] = Field(..., alias='blockReasons')


class TonightTarget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target: Target
    visibility: TargetVisibility


class TonightTargetList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[TonightTarget]
    evaluated_at: AwareDatetime = Field(..., alias='evaluatedAt')


class ObservatoryMode(StrEnum):
    """
    SIMULATED is the default implementation, always. Any interface fed by the
    simulator must be visibly labelled SIMULATED OBSERVATORY. REAL is reachable
    only through an explicit, attended operator action.

    """
    simulated = 'SIMULATED'
    real = 'REAL'


class ObservatoryLinkState(StrEnum):
    """
    ONLINE = agent connected and heartbeating. DEGRADED = connected but a heartbeat
    or device check is late. OFFLINE = no agent connection.

    """
    online = 'ONLINE'
    degraded = 'DEGRADED'
    offline = 'OFFLINE'


class WeatherStatus(StrEnum):
    clear = 'CLEAR'
    cloudy = 'CLOUDY'
    unsafe = 'UNSAFE'
    unknown = 'UNKNOWN'


class WeatherSource(StrEnum):
    """
    Phase 1 requires OPERATOR at minimum. SENSOR only if a sensor is actually fitted.
    """
    operator = 'OPERATOR'
    sensor = 'SENSOR'


class WeatherState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: WeatherStatus
    source: WeatherSource
    hold_active: bool = Field(..., alias='holdActive')
    note: str | None = None
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class DeviceHealth(StrEnum):
    ok = 'OK'
    degraded = 'DEGRADED'
    fault = 'FAULT'
    disconnected = 'DISCONNECTED'
    not_configured = 'NOT_CONFIGURED'


class DeviceStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    health: DeviceHealth
    detail: str | None = Field(None, description='Short operator-facing description. Never a device address, port or credential.')


class PublicObservatoryStatus(BaseModel):
    """
    Everything a public page may know. Deliberately excludes coordinates precise
    enough to be actionable, device identity, driver state and any address.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    observatory_id: UUID = Field(..., alias='observatoryId')
    mode: ObservatoryMode
    link: ObservatoryLinkState
    weather: WeatherState
    mission_in_progress: bool | None = Field(False, alias='missionInProgress')
    current_target_name: str | None = Field(None, alias='currentTargetName', description='Public-safe display name only, and only while a mission owner has opted in.')
    last_successful_mission_at: AwareDatetime | None = Field(None, alias='lastSuccessfulMissionAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class ObservatoryTelemetry(BaseModel):
    """
    Operator-grade telemetry. Delivered to the operator console and to the mission channel in reduced form.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: ObservatoryMode
    link: ObservatoryLinkState
    mount: DeviceStatus
    camera: DeviceStatus
    focuser: DeviceStatus
    weather: WeatherState
    pointing_equatorial: EquatorialCoordinates | None = Field(None, alias='pointingEquatorial')
    pointing_horizontal: HorizontalCoordinates | None = Field(None, alias='pointingHorizontal')
    tracking: bool | None = None
    parked: bool | None = None
    slewing: bool | None = None
    focuser_position: int | None = Field(None, alias='focuserPosition')
    ambient_temperature_c: float | None = Field(None, alias='ambientTemperatureC')
    agent_version: str | None = Field(None, alias='agentVersion')
    reported_at: AwareDatetime = Field(..., alias='reportedAt')


class SetObservatoryModeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: ObservatoryMode
    reason: str = Field(..., description='Recorded verbatim in the audit log.', min_length=8)
    attended_operator_present: bool = Field(..., alias='attendedOperatorPresent', description='Must be true to select REAL. It asserts that a human operator is physically\npresent at the observatory for this action. A background or autonomous\nprocess may never set it.\n')


class HorizonMaskEntry(BaseModel):
    """
    One bearing from the compass survey of the installation site.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    azimuth_degrees: float = Field(..., alias='azimuthDegrees', ge=0.0, lt=360.0)
    min_altitude_degrees: float = Field(..., alias='minAltitudeDegrees', ge=0.0, le=90.0)


class AzimuthSector(BaseModel):
    """
    Inclusive-start, exclusive-end sector, measured clockwise from north.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    from_degrees: float = Field(..., alias='fromDegrees', ge=0.0, lt=360.0)
    to_degrees: float = Field(..., alias='toDegrees', ge=0.0, lt=360.0)


class SafetyEnvelopeConfig(BaseModel):
    """
    The numbers that stop the telescope destroying itself. Enforced by pure
    functions in the agent and independently pre-checked by the cloud. Every field
    here is a measured or surveyed value for one physical installation. Nothing in
    this schema may carry a shipped default that would let an unmeasured system
    move.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    observatory_id: UUID = Field(..., alias='observatoryId')
    min_altitude_degrees: float = Field(..., alias='minAltitudeDegrees', description='Below this, extinction and local obstructions ruin the image.', ge=0.0, le=90.0)
    max_altitude_degrees: float | None = Field(..., alias='maxAltitudeDegrees', description='MAX_ALT_SAFE. MEASURED from the physical optical train, never guessed and\nnever defaulted. `null` means UNMEASURED: while it is null, both cloud and\nagent MUST refuse every slew command with SAFETY_NOT_CONFIGURED. Setting it\nrequires measuredAt and measuredBy.\n', ge=0.0, le=90.0)
    max_altitude_measured_at: AwareDatetime | None = Field(None, alias='maxAltitudeMeasuredAt')
    max_altitude_measured_by: str | None = Field(None, alias='maxAltitudeMeasuredBy', description='Identity of the operator who performed the physical clearance measurement.')
    max_altitude_measurement_note: str | None = Field(None, alias='maxAltitudeMeasurementNote', description='How the value was obtained, including the clearance actually observed.')
    horizon_mask: list[HorizonMaskEntry] = Field(..., alias='horizonMask', description='Minimum altitude by bearing, built from the site compass survey.')
    forbidden_azimuth_sectors: list[AzimuthSector] = Field(..., alias='forbiddenAzimuthSectors', description='Cable-wrap exclusion sectors. The mount routes the long way round rather than crossing one.')
    sun_exclusion_degrees: float = Field(..., alias='sunExclusionDegrees', description='Hard block on any coordinate within this angle of the Sun, computed\nindependently by cloud and agent. Never overridable, including by an\noperator override.\n', ge=0.0, le=180.0)
    daylight_lock_sun_altitude_degrees: float = Field(..., alias='daylightLockSunAltitudeDegrees', description='No customer mission may start while the Sun is above this altitude. An\noperator override is permitted for attended terrestrial testing and remains\nSun-bounded.\n')
    nudge_max_degrees: float = Field(..., alias='nudgeMaxDegrees', description='Cumulative offset a customer may apply from the locked target before the control re-centres.', gt=0.0)
    nudge_rate_degrees_per_second: float = Field(..., alias='nudgeRateDegreesPerSecond', description='Discrete bounded steps only. No continuous slew is ever exposed to a customer.', gt=0.0)
    slew_timeout_seconds: int = Field(..., alias='slewTimeoutSeconds', gt=0)
    heartbeat_loss_seconds: int = Field(..., alias='heartbeatLossSeconds', description='Heartbeat gap after which capture stops and the operator is alerted.', gt=0)
    link_dead_seconds: int = Field(..., alias='linkDeadSeconds', description='Link gap after which the agent Parks unconditionally, with no cloud involvement.', gt=0)
    refocus_temperature_delta_c: float = Field(..., alias='refocusTemperatureDeltaC', gt=0.0)
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class SetWeatherHoldRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hold_active: bool = Field(..., alias='holdActive')
    status: WeatherStatus
    note: str | None = None


class SlotUnavailableReason(StrEnum):
    already_booked = 'ALREADY_BOOKED'
    outside_astronomical_darkness = 'OUTSIDE_ASTRONOMICAL_DARKNESS'
    weather_hold = 'WEATHER_HOLD'
    observatory_offline = 'OBSERVATORY_OFFLINE'
    maintenance = 'MAINTENANCE'
    in_the_past = 'IN_THE_PAST'


class BookingStatus(StrEnum):
    pending_payment = 'PENDING_PAYMENT'
    confirmed = 'CONFIRMED'
    cancelled = 'CANCELLED'
    expired = 'EXPIRED'
    refunded = 'REFUNDED'


class Booking(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    user_id: UUID = Field(..., alias='userId')
    target_id: UUID = Field(..., alias='targetId')
    slot_start_at: AwareDatetime = Field(..., alias='slotStartAt')
    duration_minutes: int = Field(..., alias='durationMinutes', gt=0)
    status: BookingStatus
    price_minor: int = Field(..., alias='priceMinor', ge=0)
    currency: Currency
    payment_id: UUID | None = Field(None, alias='paymentId')
    mission_id: UUID | None = Field(None, alias='missionId')
    created_at: AwareDatetime = Field(..., alias='createdAt')


class CreateBookingRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target_id: UUID = Field(..., alias='targetId')
    slot_start_at: AwareDatetime = Field(..., alias='slotStartAt')
    duration_minutes: int = Field(..., alias='durationMinutes', gt=0)
    locale: Locale | None = None


class CancelBookingRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: str | None = None


class PaymentProvider(StrEnum):
    """
    SANDBOX is the development and CI provider. It is never selectable in a
    production environment and a production payment success is never simulated.

    """
    sandbox = 'SANDBOX'
    bog_ipay = 'BOG_IPAY'


class PaymentStatus(StrEnum):
    pending = 'PENDING'
    authorized = 'AUTHORIZED'
    captured = 'CAPTURED'
    failed = 'FAILED'
    refunded = 'REFUNDED'


class PaymentIntent(BaseModel):
    """
    The minimum a client needs to continue a payment. `redirectUrl` is supplied by
    the provider. No provider-specific field is modelled here because none has been
    confirmed against provider documentation.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    payment_id: UUID = Field(..., alias='paymentId')
    provider: PaymentProvider
    status: PaymentStatus
    redirect_url: AnyUrl | None = Field(None, alias='redirectUrl')
    expires_at: AwareDatetime | None = Field(None, alias='expiresAt')


class BookingWithPaymentIntent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    booking: Booking
    payment_intent: PaymentIntent = Field(..., alias='paymentIntent')


class BookingPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Booking]
    page: PageMeta


class PaymentWebhookEnvelope(BaseModel):
    """
    The provider's body is opaque on purpose. The cloud verifies the signature over
    the raw body, then maps the payload to Darkview's own Payment record. Do not add
    provider fields to this schema before they are confirmed against the provider's
    published documentation.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    provider: PaymentProvider
    payload: dict[str, Any] = Field(..., description='Provider-defined, unvalidated by Darkview beyond signature verification.')


class PaymentWebhookAck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    received: bool


class MissionState(StrEnum):
    """
    The authoritative mission state machine, exactly as enumerated in CLAUDE.md.

    Primary:  REQUESTED -> SCHEDULED -> PREPARING -> SLEWING -> VERIFYING ->
              CENTERING -> OBSERVING -> CAPTURING -> PROCESSING -> COMPLETE
    Failure / hold: WEATHER_HOLD, NOT_VISIBLE, HARDWARE_ERROR, CANCELLED, FAILED

    VERIFYING is the ASTAP plate-solve step. CENTERING applies the solved offset and
    re-slews, bounded to three iterations. Any state may enter a failure or hold
    state, and every path out of one ends at Park.

    Resolved by docs/decisions/ADR-004-mission-state-machine.md (2026-08-31). This
    enum matches CLAUDE.md and nothing else. The Build Plan's LOCKED and DELIVERED
    are not states -- "Target locked" and "LIVE" are display labels mapped in the
    web layer. Its SOLVE_FAILED, LINK_LOST and EXPIRED are carried as
    MissionFailureReason detail on a state above, never as states.

    """
    requested = 'REQUESTED'
    scheduled = 'SCHEDULED'
    preparing = 'PREPARING'
    slewing = 'SLEWING'
    verifying = 'VERIFYING'
    centering = 'CENTERING'
    observing = 'OBSERVING'
    capturing = 'CAPTURING'
    processing = 'PROCESSING'
    complete = 'COMPLETE'
    weather_hold = 'WEATHER_HOLD'
    not_visible = 'NOT_VISIBLE'
    hardware_error = 'HARDWARE_ERROR'
    cancelled = 'CANCELLED'
    failed = 'FAILED'


class MissionFailureReason(StrEnum):
    """
    Diagnostic detail attached to a failure or hold state. This is NOT a state and
    must never be used as one, mapped into MissionState, or displayed as a stage in
    a progress indicator.

    """
    plate_solve_failed = 'PLATE_SOLVE_FAILED'
    slew_timeout = 'SLEW_TIMEOUT'
    centering_iterations_exhausted = 'CENTERING_ITERATIONS_EXHAUSTED'
    tracking_lost = 'TRACKING_LOST'
    mount_fault = 'MOUNT_FAULT'
    camera_fault = 'CAMERA_FAULT'
    focuser_fault = 'FOCUSER_FAULT'
    agent_link_lost = 'AGENT_LINK_LOST'
    heartbeat_lost = 'HEARTBEAT_LOST'
    safety_refused = 'SAFETY_REFUSED'
    safety_envelope_unmeasured = 'SAFETY_ENVELOPE_UNMEASURED'
    target_set_below_limit = 'TARGET_SET_BELOW_LIMIT'
    weather_unsafe = 'WEATHER_UNSAFE'
    session_expired = 'SESSION_EXPIRED'
    operator_abort = 'OPERATOR_ABORT'
    customer_cancelled = 'CUSTOMER_CANCELLED'
    payment_failed = 'PAYMENT_FAILED'


class Mission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    user_id: UUID = Field(..., alias='userId')
    booking_id: UUID = Field(..., alias='bookingId')
    target_id: UUID = Field(..., alias='targetId')
    observatory_id: UUID = Field(..., alias='observatoryId')
    state: MissionState
    failure_reason: MissionFailureReason | None = Field(None, alias='failureReason')
    mode: ObservatoryMode
    scheduled_start_at: AwareDatetime | None = Field(None, alias='scheduledStartAt')
    requested_at: AwareDatetime = Field(..., alias='requestedAt')
    started_at: AwareDatetime | None = Field(None, alias='startedAt')
    ended_at: AwareDatetime | None = Field(None, alias='endedAt')
    capture_ids: list[UUID] | None = Field(None, alias='captureIds')
    observable: bool | None = Field(False, description='Whether the controller has opted this session in to being observed. Sessions\nare PRIVATE by default (ADR-007). Only the session owner may change it.\n')
    observer_capacity: int | None = Field(5, alias='observerCapacity', description='Hard server-side cap on concurrent observers. Never exceeds 5 (ADR-007).', ge=0, le=5)
    observer_count: int | None = Field(None, alias='observerCount', description='Observers currently attached. Never exceeds observerCapacity.', ge=0)


class MissionPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Mission]
    page: PageMeta


class SessionRole(StrEnum):
    """
    Who a person is on a live mission. Exactly one CONTROLLER exists at a time -- that
    is the session owner, and the only identity for which the cloud will mint a
    CommandEnvelope. An OBSERVER watches and can never command: the agent rejects any
    envelope whose sessionId is not the current owner, independently of the cloud.

    """
    controller = 'CONTROLLER'
    observer = 'OBSERVER'


class MissionObserver(BaseModel):
    """
    A paid, view-only seat on a session somebody else controls (ADR-007).
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    mission_id: UUID = Field(..., alias='missionId')
    user_id: UUID = Field(..., alias='userId')
    joined_at: AwareDatetime = Field(..., alias='joinedAt')
    left_at: AwareDatetime | None = Field(None, alias='leftAt')


class MissionObserverList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[MissionObserver]
    capacity: int = Field(..., ge=0, le=5)


class MissionObservationSettings(BaseModel):
    """
    The controller's consent to being observed. Set only by the session owner.
    Sessions are private by default and become observable only by this call.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    observable: bool


class MissionEventSource(StrEnum):
    cloud = 'CLOUD'
    agent = 'AGENT'
    operator = 'OPERATOR'


class MissionEvent(BaseModel):
    """
    One correlated entry in the mission audit trail. Never fabricated or backdated.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    mission_id: UUID = Field(..., alias='missionId')
    at: AwareDatetime
    state: MissionState
    failure_reason: MissionFailureReason | None = Field(None, alias='failureReason')
    source: MissionEventSource
    command_id: UUID | None = Field(None, alias='commandId')
    detail: str | None = None


class MissionEventPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[MissionEvent]
    page: PageMeta


class CommandType(StrEnum):
    """
    The complete set of instruction types the cloud may send to the agent. A client
    may only cause a subset of these to be minted; see ClientCommandType.

    """
    goto = 'GOTO'
    nudge = 'NUDGE'
    capture = 'CAPTURE'
    focus = 'FOCUS'
    abort = 'ABORT'
    park = 'PARK'
    set_profile = 'SET_PROFILE'


class ClientCommandType(StrEnum):
    """
    What a customer may ask for during a live observation. GOTO, FOCUS, PARK and
    SET_PROFILE are never client-initiated: the target comes from the booking and
    the rest are cloud or operator concerns. RECENTER is translated by the cloud
    into a GOTO back to the booked target; it is not a free-form slew.

    """
    nudge = 'NUDGE'
    capture = 'CAPTURE'
    recenter = 'RECENTER'
    abort = 'ABORT'


class NudgeAxis(StrEnum):
    altitude = 'ALTITUDE'
    azimuth = 'AZIMUTH'


class NudgeDirection(StrEnum):
    positive = 'POSITIVE'
    negative = 'NEGATIVE'


class FocusMode(StrEnum):
    autofocus = 'AUTOFOCUS'
    absolute = 'ABSOLUTE'


class RegionOfInterest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: int = Field(..., ge=0)
    y: int = Field(..., ge=0)
    width: int = Field(..., gt=0)
    height: int = Field(..., gt=0)


class GotoPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['GOTO']
    target_id: UUID = Field(..., alias='targetId')
    coordinates: EquatorialCoordinates
    optical_config: OpticalConfig = Field(..., alias='opticalConfig')
    imaging_profile: ImagingProfile = Field(..., alias='imagingProfile')
    recenter: bool | None = Field(False, description='True when this GOTO returns the mount to the booked target after customer nudges.')


class NudgePayload(BaseModel):
    """
    One discrete bounded step. Never a continuous slew.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['NUDGE']
    axis: NudgeAxis
    direction: NudgeDirection
    step_arcminutes: float = Field(..., alias='stepArcminutes', description='Bounded by SafetyEnvelopeConfig.nudgeMaxDegrees cumulatively and by nudgeRateDegreesPerSecond instantaneously.', gt=0.0)


class CapturePayload(BaseModel):
    """
    Phase 1 capture is a short-exposure / live-stacking run, not a long exposure.
    The requested integration is bounded by the imaging profile.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['CAPTURE']
    imaging_profile: ImagingProfile = Field(..., alias='imagingProfile')
    requested_frames: int | None = Field(None, alias='requestedFrames', gt=0)
    target_integration_seconds: float | None = Field(None, alias='targetIntegrationSeconds', gt=0.0)


class FocusPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['FOCUS']
    mode: FocusMode
    absolute_position: int | None = Field(None, alias='absolutePosition', description='Required when mode is ABSOLUTE. The agent applies backlash compensation with a same-direction final approach.')


class AbortPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['ABORT']
    reason: str | None = None


class ParkPayload(BaseModel):
    """
    Park is the answer to every unresolved condition.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['PARK']
    reason: str | None = None


class SetProfilePayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['SET_PROFILE']
    imaging_profile: ImagingProfile = Field(..., alias='imagingProfile')
    exposure_milliseconds: float | None = Field(None, alias='exposureMilliseconds', description="Short exposures only. Alt-azimuth field rotation, not the sensor, sets the\nceiling. Values beyond the profile's documented range are refused.\n", gt=0.0)
    gain: int | None = Field(None, ge=0)
    region_of_interest: RegionOfInterest | None = Field(None, alias='regionOfInterest')


class CommandPayload(RootModel[GotoPayload | NudgePayload | CapturePayload | FocusPayload | AbortPayload | ParkPayload | SetProfilePayload]):
    root: GotoPayload | NudgePayload | CapturePayload | FocusPayload | AbortPayload | ParkPayload | SetProfilePayload = Field(..., description="Discriminated by `kind`. `payload.kind` MUST equal the envelope's `type`; both\nthe cloud and the agent reject an envelope where they disagree.\n", discriminator='kind')


class CommandEnvelope(BaseModel):
    """
    The only structure by which anything may instruct the observatory.

    Minted exclusively by the Darkview cloud. A browser or mobile client never
    constructs one and never sees a device address inside one.

    The agent enforces all of the following independently of the cloud:
      - idempotent by commandId; a repeat of a seen commandId is ignored;
      - rejected after expiresAt;
      - rejected if sessionId is not the current session owner;
      - rejected if userId does not match the session owner;
      - rejected if missionId is not the mission the agent currently holds;
      - rejected if the safety envelope refuses it, even when the cloud approved it.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID = Field(..., alias='commandId', description='Idempotency key. The agent keeps a seen-set so retries are safe.')
    mission_id: UUID = Field(..., alias='missionId')
    session_id: UUID = Field(..., alias='sessionId')
    user_id: UUID = Field(..., alias='userId')
    issued_at: AwareDatetime = Field(..., alias='issuedAt')
    expires_at: AwareDatetime = Field(..., alias='expiresAt', description='Short-lived. A queued command must not fire after a reconnect.')
    type: CommandType
    payload: CommandPayload
    issued_by_operator_id: UUID | None = Field(None, alias='issuedByOperatorId', description='Set only for an operator override. Present on every separately audited command.')
    override_reason: str | None = Field(None, alias='overrideReason', description='Required when issuedByOperatorId is set. Recorded verbatim in the audit log.')


class MissionCommandRequest(BaseModel):
    """
    Client intent. Deliberately does NOT contain commandId, sessionId, userId,
    issuedAt or expiresAt: the cloud sets all of those. A client that supplies them
    is rejected.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: ClientCommandType
    nudge: NudgePayload | None = None
    capture: CapturePayload | None = None
    reason: str | None = None


class CommandAcceptanceStatus(StrEnum):
    accepted = 'ACCEPTED'
    rejected = 'REJECTED'
    duplicate = 'DUPLICATE'
    expired = 'EXPIRED'
    completed = 'COMPLETED'
    failed = 'FAILED'


class CommandRejectionReason(StrEnum):
    """
    Why a command was refused. The SAFETY_ prefixed values are produced by the
    agent's own envelope check and may occur even when the cloud approved the
    command; that is the design, not a bug.

    """
    duplicate_command_id = 'DUPLICATE_COMMAND_ID'
    command_expired = 'COMMAND_EXPIRED'
    wrong_session = 'WRONG_SESSION'
    wrong_user = 'WRONG_USER'
    wrong_mission = 'WRONG_MISSION'
    no_active_mission = 'NO_ACTIVE_MISSION'
    mission_already_active = 'MISSION_ALREADY_ACTIVE'
    payload_type_mismatch = 'PAYLOAD_TYPE_MISMATCH'
    malformed_payload = 'MALFORMED_PAYLOAD'
    command_not_permitted_for_client = 'COMMAND_NOT_PERMITTED_FOR_CLIENT'
    safety_envelope_unmeasured = 'SAFETY_ENVELOPE_UNMEASURED'
    safety_below_min_altitude = 'SAFETY_BELOW_MIN_ALTITUDE'
    safety_above_max_altitude = 'SAFETY_ABOVE_MAX_ALTITUDE'
    safety_horizon_mask = 'SAFETY_HORIZON_MASK'
    safety_forbidden_azimuth = 'SAFETY_FORBIDDEN_AZIMUTH'
    safety_sun_exclusion = 'SAFETY_SUN_EXCLUSION'
    safety_daylight_lock = 'SAFETY_DAYLIGHT_LOCK'
    safety_nudge_limit_exceeded = 'SAFETY_NUDGE_LIMIT_EXCEEDED'
    safety_slew_rate = 'SAFETY_SLEW_RATE'
    device_unavailable = 'DEVICE_UNAVAILABLE'
    mode_not_permitted = 'MODE_NOT_PERMITTED'
    weather_hold_active = 'WEATHER_HOLD_ACTIVE'
    observatory_offline = 'OBSERVATORY_OFFLINE'


class MissionCommandAccepted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID = Field(..., alias='commandId')
    mission_id: UUID = Field(..., alias='missionId')
    type: CommandType
    issued_at: AwareDatetime = Field(..., alias='issuedAt')
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    status: CommandAcceptanceStatus
    rejection_reason: CommandRejectionReason | None = Field(None, alias='rejectionReason')


class OperatorOverrideRequest(BaseModel):
    """
    Manual operator control. Still safety-bounded; the Sun exclusion is never
    overridable. Requires a stated reason, which is stored in the audit log.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    mission_id: UUID | None = Field(None, alias='missionId', description='Null for a standalone maintenance action outside any mission.')
    type: CommandType
    payload: CommandPayload
    reason: str = Field(..., min_length=8)


class CaptureAssetKind(StrEnum):
    """
    IMAGE is the delivered, stretched, watermarked image. FITS is the real frame
    data. UNMARKED is the stored copy without the overlay.

    """
    image = 'IMAGE'
    thumbnail = 'THUMBNAIL'
    fits = 'FITS'
    unmarked = 'UNMARKED'


class CaptureVisibility(StrEnum):
    """
    PRIVATE by default. Publishing to the public gallery is opt-in.
    """
    private = 'PRIVATE'
    gallery = 'GALLERY'


class Capture(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    mission_id: UUID = Field(..., alias='missionId')
    user_id: UUID = Field(..., alias='userId')
    target_id: UUID = Field(..., alias='targetId')
    captured_at: AwareDatetime = Field(..., alias='capturedAt')
    imaging_profile: ImagingProfile = Field(..., alias='imagingProfile')
    optical_config: OpticalConfig = Field(..., alias='opticalConfig')
    exposure_milliseconds: float = Field(..., alias='exposureMilliseconds', gt=0.0)
    gain: int = Field(..., ge=0)
    frames_stacked: int = Field(..., alias='framesStacked', gt=0)
    integration_seconds: float = Field(..., alias='integrationSeconds', gt=0.0)
    width_px: int | None = Field(None, alias='widthPx')
    height_px: int | None = Field(None, alias='heightPx')
    solved_focal_length_mm: float | None = Field(None, alias='solvedFocalLengthMm', description='Read back from the plate solve. Confirms which optical configuration was actually in the train.')
    fits_available: bool = Field(..., alias='fitsAvailable')
    visibility: CaptureVisibility
    mode: ObservatoryMode = Field(..., description='A capture produced by the simulator is permanently marked SIMULATED. It is\nnever presented as telescope output and never used as audit evidence of real\nhardware.\n')
    thumbnail_url: AnyUrl | None = Field(None, alias='thumbnailUrl', description='Signed, short-expiry URL. Never a public bucket path.')


class CapturePage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Capture]
    page: PageMeta


class CaptureDownload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: CaptureAssetKind
    url: AnyUrl
    expires_at: AwareDatetime = Field(..., alias='expiresAt')


class AuditCategory(StrEnum):
    auth = 'AUTH'
    booking = 'BOOKING'
    payment = 'PAYMENT'
    mission = 'MISSION'
    command = 'COMMAND'
    safety = 'SAFETY'
    observatory_mode = 'OBSERVATORY_MODE'
    operator_override = 'OPERATOR_OVERRIDE'
    agent_link = 'AGENT_LINK'


class AuditEvent(BaseModel):
    """
    Append-only. Never edited, never backdated, never fabricated.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    at: AwareDatetime
    category: AuditCategory
    action: str
    actor_user_id: UUID | None = Field(None, alias='actorUserId')
    mission_id: UUID | None = Field(None, alias='missionId')
    command_id: UUID | None = Field(None, alias='commandId')
    detail: dict[str, Any] | None = Field(None, description='Structured detail. Never contains a secret, token or device address.')


class AuditEventPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[AuditEvent]
    page: PageMeta


class WebSocketProtocolVersion(RootModel[Literal['1']]):
    root: Literal['1'] = Field(..., description='Incremented on any breaking change to the agent link message set. The cloud refuses an agent whose version it does not support.')


class AgentHello(BaseModel):
    """
    First message after the agent dials out and authenticates.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['AGENT_HELLO']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    protocol_version: WebSocketProtocolVersion = Field(..., alias='protocolVersion')
    observatory_id: UUID = Field(..., alias='observatoryId')
    agent_version: str = Field(..., alias='agentVersion')
    mode: ObservatoryMode
    booted_at: AwareDatetime = Field(..., alias='bootedAt')
    safety_envelope_configured: bool | None = Field(None, alias='safetyEnvelopeConfigured', description='False while maxAltitudeDegrees is unmeasured. The cloud must not schedule a mission against an agent reporting false.')
    resume_mission_id: UUID | None = Field(None, alias='resumeMissionId', description='Set when the agent restarts holding a mission recovered from its local state store.')


class AgentHeartbeat(BaseModel):
    """
    Sent every 5 seconds. Its absence is what triggers the watchdog.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['AGENT_HEARTBEAT']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    sequence: int = Field(..., ge=0)
    uptime_seconds: int = Field(..., alias='uptimeSeconds', ge=0)


class AgentCommandAck(BaseModel):
    """
    The agent's independent verdict on one command. A REJECTED ack with a SAFETY_
    reason after the cloud approved the command is the safety design working.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['AGENT_COMMAND_ACK']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    command_id: UUID = Field(..., alias='commandId')
    mission_id: UUID | None = Field(None, alias='missionId')
    status: CommandAcceptanceStatus
    rejection_reason: CommandRejectionReason | None = Field(None, alias='rejectionReason')
    detail: str | None = None


class AgentStateDelta(BaseModel):
    """
    Emitted on the agent control loop. Carries telemetry and, if a mission is held, its state.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['AGENT_STATE_DELTA']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    telemetry: ObservatoryTelemetry
    mission_id: UUID | None = Field(None, alias='missionId')
    mission_state: MissionState | None = Field(None, alias='missionState')
    failure_reason: MissionFailureReason | None = Field(None, alias='failureReason')
    centering_iteration: int | None = Field(None, alias='centeringIteration', description='Current plate-solve / re-slew iteration, capped at three.', ge=0)
    residual_arcminutes: float | None = Field(None, alias='residualArcminutes', description='Distance between the solved position and the target after the last iteration.')


class AgentMissionEvent(BaseModel):
    """
    A state transition the agent wants written to the mission audit trail.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['AGENT_MISSION_EVENT']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    state: MissionState
    failure_reason: MissionFailureReason | None = Field(None, alias='failureReason')
    occurred_at: AwareDatetime = Field(..., alias='occurredAt', description='When it actually happened on the observatory clock. Replayed unchanged after a reconnect; never rewritten to look contemporaneous.')
    command_id: UUID | None = Field(None, alias='commandId')
    detail: str | None = None


class LiveFrameEncoding(RootModel[Literal['JPEG']]):
    root: Literal['JPEG'] = Field(..., description='Phase 1 delivers MJPEG. WebRTC is a Phase 2 change and requires an approved decision record.')


class LiveFrameHeader(BaseModel):
    """
    Metadata for exactly one live-view frame. The encoded bytes follow as the very
    next binary WebSocket frame on the same connection. Pixel data is never
    base64-encoded into JSON.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['AGENT_LIVE_FRAME']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    sequence: int = Field(..., ge=0)
    captured_at: AwareDatetime = Field(..., alias='capturedAt')
    encoding: LiveFrameEncoding
    width_px: int = Field(..., alias='widthPx', gt=0)
    height_px: int = Field(..., alias='heightPx', gt=0)
    byte_length: int = Field(..., alias='byteLength', gt=0)
    exposure_milliseconds: float = Field(..., alias='exposureMilliseconds', gt=0.0)
    gain: int = Field(..., ge=0)
    stacked_frames: int | None = Field(None, alias='stackedFrames', description='Set when the frame is a live stack rather than a single sub-exposure.', gt=0)
    mode: ObservatoryMode = Field(..., description='A frame produced by SimCamera is marked SIMULATED and any UI showing it must say so.')


class AgentCaptureReady(BaseModel):
    """
    A finished capture has been uploaded by the agent and is ready for the cloud to record.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['AGENT_CAPTURE_READY']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    command_id: UUID = Field(..., alias='commandId')
    captured_at: AwareDatetime = Field(..., alias='capturedAt')
    imaging_profile: ImagingProfile = Field(..., alias='imagingProfile')
    optical_config: OpticalConfig = Field(..., alias='opticalConfig')
    exposure_milliseconds: float = Field(..., alias='exposureMilliseconds', gt=0.0)
    gain: int = Field(..., ge=0)
    frames_stacked: int = Field(..., alias='framesStacked', gt=0)
    integration_seconds: float = Field(..., alias='integrationSeconds', gt=0.0)
    image_storage_key: str = Field(..., alias='imageStorageKey', description='Object storage key written by the agent. Not a URL and never a public path.')
    unmarked_storage_key: str | None = Field(None, alias='unmarkedStorageKey')
    fits_storage_key: str | None = Field(None, alias='fitsStorageKey')
    solved_focal_length_mm: float | None = Field(None, alias='solvedFocalLengthMm')
    width_px: int | None = Field(None, alias='widthPx')
    height_px: int | None = Field(None, alias='heightPx')
    mode: ObservatoryMode


class AgentErrorSeverity(StrEnum):
    warning = 'WARNING'
    error = 'ERROR'
    fatal = 'FATAL'


class AgentError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['AGENT_ERROR']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    severity: AgentErrorSeverity
    code: str
    message: str = Field(..., description='Operator-facing. Never contains a token, credential or local address.')
    mission_id: UUID | None = Field(None, alias='missionId')
    command_id: UUID | None = Field(None, alias='commandId')


class AgentToCloudMessage(RootModel[AgentHello | AgentHeartbeat | AgentCommandAck | AgentStateDelta | AgentMissionEvent | LiveFrameHeader | AgentCaptureReady | AgentError]):
    root: AgentHello | AgentHeartbeat | AgentCommandAck | AgentStateDelta | AgentMissionEvent | LiveFrameHeader | AgentCaptureReady | AgentError = Field(..., description='Every message the Observatory Agent may send over its outbound link.', discriminator='type')


class CloudWelcome(BaseModel):
    """
    Cloud response to AgentHello. Establishes the mission the agent is expected to hold, if any.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CLOUD_WELCOME']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    protocol_version: WebSocketProtocolVersion = Field(..., alias='protocolVersion')
    server_time: AwareDatetime = Field(..., alias='serverTime', description='For agent clock-skew detection. The agent never uses it to rewrite a recorded event time.')
    expected_mission_id: UUID | None = Field(None, alias='expectedMissionId')
    heartbeat_interval_seconds: int | None = Field(5, alias='heartbeatIntervalSeconds', gt=0)


class CloudCommand(BaseModel):
    """
    The only way the cloud instructs the observatory.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CLOUD_COMMAND']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    command: CommandEnvelope


class CloudHeartbeatAck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CLOUD_HEARTBEAT_ACK']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    sequence: int = Field(..., ge=0)


class CloudSessionUpdate(BaseModel):
    """
    Tells the agent who the single active session owner is. The agent refuses any
    command whose sessionId does not match the value it last received here, which is
    what stops a stale browser tab.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CLOUD_SESSION_UPDATE']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    session_id: UUID | None = Field(None, alias='sessionId', description='Null revokes the session. The agent then accepts no client-originated command for this mission.')
    user_id: UUID | None = Field(None, alias='userId')
    expires_at: AwareDatetime | None = Field(None, alias='expiresAt')


class CloudSafetyEnvelopeUpdate(BaseModel):
    """
    Distributes the measured envelope to the agent. The agent stores it locally and
    keeps enforcing it after the cloud link dies. Receiving an envelope whose
    maxAltitudeDegrees is null puts the agent in the refuse-all-slews state.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CLOUD_SAFETY_ENVELOPE_UPDATE']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    envelope: SafetyEnvelopeConfig


class CloudError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CLOUD_ERROR']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    code: ErrorCode
    message: str
    fatal: bool | None = Field(False, description='When true the agent closes the link, backs off and re-dials. It does not stop enforcing safety while disconnected.')


class CloudToAgentMessage(RootModel[CloudWelcome | CloudCommand | CloudHeartbeatAck | CloudSessionUpdate | CloudSafetyEnvelopeUpdate | CloudError]):
    root: CloudWelcome | CloudCommand | CloudHeartbeatAck | CloudSessionUpdate | CloudSafetyEnvelopeUpdate | CloudError = Field(..., description='Every message the cloud may send down the agent link.', discriminator='type')


class MissionStateUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['MISSION_STATE']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    state: MissionState
    failure_reason: MissionFailureReason | None = Field(None, alias='failureReason')
    remaining_seconds: int | None = Field(None, alias='remainingSeconds', ge=0)


class MissionTelemetryUpdate(BaseModel):
    """
    Client-safe telemetry. Deliberately narrower than ObservatoryTelemetry: no
    device identity, no driver state, no address.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['MISSION_TELEMETRY']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    mode: ObservatoryMode
    link: ObservatoryLinkState
    tracking: bool | None = None
    centering_iteration: int | None = Field(None, alias='centeringIteration', ge=0)
    residual_arcminutes: float | None = Field(None, alias='residualArcminutes')
    nudge_used_degrees: float | None = Field(None, alias='nudgeUsedDegrees', ge=0.0)
    ambient_temperature_c: float | None = Field(None, alias='ambientTemperatureC')


class MissionStreamInfo(BaseModel):
    """
    Where the client reads the live view. A short-expiry signed URL, never a device address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['MISSION_STREAM']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    stream_url: AnyUrl = Field(..., alias='streamUrl')
    encoding: LiveFrameEncoding
    mode: ObservatoryMode
    expires_at: AwareDatetime = Field(..., alias='expiresAt')


class MissionCaptureReady(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['MISSION_CAPTURE_READY']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    capture: Capture


class MissionCommandResult(BaseModel):
    """
    The outcome of a command the client submitted over HTTP, delivered asynchronously.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['MISSION_COMMAND_RESULT']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    command_id: UUID = Field(..., alias='commandId')
    status: CommandAcceptanceStatus
    rejection_reason: CommandRejectionReason | None = Field(None, alias='rejectionReason')


class MissionChannelError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['MISSION_ERROR']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    code: ErrorCode
    message: str


class MissionChannelMessage(RootModel[MissionStateUpdate | MissionTelemetryUpdate | MissionStreamInfo | MissionCaptureReady | MissionCommandResult | MissionChannelError]):
    root: MissionStateUpdate | MissionTelemetryUpdate | MissionStreamInfo | MissionCaptureReady | MissionCommandResult | MissionChannelError = Field(..., description='Everything the cloud pushes to a subscribed live-mission client.', discriminator='type')


class MissionClientSubscribe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CLIENT_SUBSCRIBE']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')
    mission_id: UUID = Field(..., alias='missionId')
    session_id: UUID = Field(..., alias='sessionId')


class MissionClientPing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['CLIENT_PING']
    message_id: UUID = Field(..., alias='messageId')
    sent_at: AwareDatetime = Field(..., alias='sentAt')


class MissionClientMessage(RootModel[MissionClientSubscribe | MissionClientPing]):
    root: MissionClientSubscribe | MissionClientPing = Field(..., description='The complete set of messages a client may send on the mission channel. It is\ndeliberately tiny: subscribe and keep-alive. A client may not send a\nCommandEnvelope, a device instruction or any hardware-shaped value here.\n', discriminator='type')


class Resolution(StrEnum):
    refund = 'REFUND'
    reschedule = 'RESCHEDULE'
    none = 'NONE'


class AdminCancelMissionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: str = Field(..., min_length=4)
    resolution: Resolution


class AdminUpdateTargetRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool | None = None
    imaging_profile: ImagingProfile | None = Field(None, alias='imagingProfile')
    optical_config: OpticalConfig | None = Field(None, alias='opticalConfig')
    min_altitude_degrees: float | None = Field(None, alias='minAltitudeDegrees', ge=0.0, le=90.0)
    expected_mission_minutes: int | None = Field(None, alias='expectedMissionMinutes', gt=0)
    preview_image_url: AnyUrl | None = Field(None, alias='previewImageUrl')
    description_en: str | None = Field(None, alias='descriptionEn')
    description_ka: str | None = Field(None, alias='descriptionKa')


class OperatorObservatoryState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    observatory_id: UUID = Field(..., alias='observatoryId')
    telemetry: ObservatoryTelemetry
    safety_envelope: SafetyEnvelopeConfig = Field(..., alias='safetyEnvelope')
    active_mission_id: UUID | None = Field(None, alias='activeMissionId')
    active_session_id: UUID | None = Field(None, alias='activeSessionId')
    link_latency_ms: int | None = Field(None, alias='linkLatencyMs')
    last_heartbeat_at: AwareDatetime | None = Field(None, alias='lastHeartbeatAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class Slot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start_at: AwareDatetime = Field(..., alias='startAt')
    end_at: AwareDatetime = Field(..., alias='endAt')
    duration_minutes: int = Field(..., alias='durationMinutes', gt=0)
    available: bool
    price_minor: int = Field(..., alias='priceMinor', description='Price in the minor unit of `currency` (tetri for GEL). Never a float.', ge=0)
    currency: Currency
    unavailable_reason: SlotUnavailableReason | None = Field(None, alias='unavailableReason')


class SlotList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: date_aliased
    items: list[Slot]


class MissionSession(BaseModel):
    """
    Proof that this client is the single active session owner. The session
    identifier is minted by the cloud and is required on every CommandEnvelope. It
    is not a device credential and gives no access to hardware.

    """
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: UUID = Field(..., alias='sessionId')
    mission_id: UUID = Field(..., alias='missionId')
    user_id: UUID = Field(..., alias='userId')
    issued_at: AwareDatetime = Field(..., alias='issuedAt')
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    mission_channel_url: str = Field(..., alias='missionChannelUrl', description="Relative WSS path for this mission's client channel.")
    allowed_commands: list[ClientCommandType] | None = Field(None, alias='allowedCommands')
